### ISSUE TITLE
GOA to GOC pipeline checks and tasks

### ISSUE THREAD

**Issue by hattrill** [FlyBase/GO-curation#144]
Aim: for Dmel annotations in GOA to go straight into GO using FBgn mappings to UniProtKB and RNAcentral IDs. CPX annotations will also go into GO via this pipeline.

This is required as:
1. Not yet ready to move to Noctua as primary annotation tool
2. Part of harmonization of GO data across species
3. Intergrating all IEA pipelines in one

Issues:
Will mean that FB displayed data will diverge from GOC data as we filter certain annotations/sources, but this will be more inline for what we need to do for transition to Alliance.

**Comment by hattrill** [comment]
TO DO:

- [x] Supply list of sources to Pascale
- [ ] Produce a GPI2.0 : NOT REQUIRED
- [x] Add xref to complex portal for Entity types = protein complexes 
- [ ] Delete unmapped loci ("gene products")  : NOT REQUIRED
- [x] Check unmapped proteins and ncRNA
- [x] Confirm that all FB entities FB wants to annotate are in GOA GPI

**Comment by hattrill** [comment]
JIRA tickets that might be useful:
[Add complexes to the gp_information.fb file with complex portal xrefs](https://flybase.atlassian.net/issues/DB-980)
[Update gp_information.fb to include other gene classes](https://flybase.atlassian.net/issues/DB-907)
[Updates to GO annotation pipeline](https://flybase.atlassian.net/issues/DB-765)
[Update the Protein2GO update pipeline to include new annotation sources](https://flybase.atlassian.net/issues/DB-767)

**Comment by hattrill** [comment]
Genes w/o UniProtKB or RNAcentral xref to check:

- [x] FBgn0287632    CG46492 **UPDATE** A0ACD4DAQ4
------
- [x] FBgn0288729    CG46504
- [x] FBgn0288730    CG46505
- [x] FBgn0288731    CG46506
- [x] FBgn0288732    CG46507
- [x] FBgn0288733    CG46508
- [x] FBgn0288734    CG46509
- [x] FBgn0288735    CG46510
- [x] FBgn0288736    CG46511
- [x] FBgn0288737    CG46512
- [x] FBgn0288738    CG46513
- [x] FBgn0288739    CG46514
- [x] FBgn0288740    CG46515
- [x] FBgn0288741    CG46516
- [x] FBgn0288742    CG46517
- [x] FBgn0288743    CG46518
- [x] FBgn0288744    CG46519
- [x] FBgn0288745    CG46520
- [x] FBgn0288746    CG46521
- [x] FBgn0288747    CG46522
-**UPDATE** See https://docs.google.com/spreadsheets/d/1-yyFXTo4XLjqLlcbg5WLpyoEd1rdQGHsmskTLX6o25E/edit?gid=0#gid=0
-----
- [x] FBgn0288835    MSAmiP **UPDATE** A0ACD4DAS6|A0ACD4DB37

Steven sent UniProt an email. Summary:
They are in GenBank, ENA and UniParc, not on UniProt website or the UP000000803_7227.idmapping file.
1. The 19 X-localised genes
- These are near-exact, tandem duplicates that all encode a 213 aa protein. Their ENA records have a date stamp of 25-JUN-2024.
- Note that the other 2 members of this array (FBgn0085521/CG40813=EDP27953) and FBgn0085693/CG41562=EDP27934) were annotated much earlier and included in a  previous GenBank submission, and these do have UniProtKB accessions (A8QI13 and A8QI32)

2. FBgn0287632/CG46492 (UYI57904)
- This is in UniParc as UPI001440E550, with FlyBase dates of “First seen 2020-04-06” and "Last seen 2024-08-21”.  
- It’s a nested gene, encoded within an intron of CG46491 (FBgn0287631)

3. FBgn0288835/MSAmiP (UYI58781,UYI58782)
- These are in UniParc as UPI002031006E/UPI0020310076, with dates of “First seen 2022-06-01” and "Last seen 2024-08-21”. 
- This is a ‘micropeptide’-encoding gene, predicted to encode 2 peptides of 9 and 20 amino acids.
- Overlaps with/is encoded by the last two exons of a ncRNA gene (lncRNA:iab8= FBgn0264857), which results in a messy-looking INSDC entry.

- [x] FBgn0289725    lncRNA:CR43126

Emailed Blake as should have been updated with FB2024_01 (which is the version they are using)

**Comment by hattrill** [comment]
Annotation sources
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/hla28/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/hla28/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

</head>

<body link="#467886" vlink="#96607D">


Sources | FB import
-- | --
FlyBase | Y
GO_Central | Y
UniProt | Y
ParkinsonsUK-UCL | Y
CACAO | Y
BHF-UCL | Y
InterPro | Y
SynGO | Y
CAFA | Y
WB | Y
HGNC-UCL | Y
HGNC | Y
MGI | Y
ARUK-UCL | Y
SGD | Y
RNAcentral | Y
GOC | N
RHEA | N
IntAct | N
Reactome | N
ComplexPortal | N
DisProt | N



</body>

</html>

**Comment by hattrill** [comment]
- In GPI v2.0, type is specified via ID rather than name. 
- We will not be able to use 'gene product' as this is not in SO. But could use 'gene' SO:0000704 instead.
Gene Model Status #Genes
Not Applicable	9
Unannotated	1250
(2798 annotations to 'gene product')
- However, we should really consider dumping most of the annotations to 'Unannotated', so this may not be a major issue.
- For status = Not Applicable with annotations:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/hla28/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/hla28/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

</head>

<body link="#467886" vlink="#96607D">


FBgn | symbol | SO | Status | DBXREF
-- | -- | -- | -- | --
FBgn0000002 | 5SrRNA | SO0002238:cytosolic_rRNA_5S_gene | Not Applicable | no RNAcentral xref
FBgn0001195 | His1 | SO0001217:protein_coding_gene | Not Applicable | UniProt/Swiss-Prot:P02255
FBgn0001196 | His2A | SO0001217:protein_coding_gene | Not Applicable | UniProt/GCRP:P84051
FBgn0001198 | His2B | SO0001217:protein_coding_gene | Not Applicable | UniProt/GCRP:P02283
FBgn0001199 | His3 | SO0001217:protein_coding_gene | Not Applicable | UniProt/GCRP:P02299
FBgn0001200 | His4 | SO0001217:protein_coding_gene | Not Applicable | UniProt/GCRP:P84040
FBgn0261516 | Sdic | SO0001217:protein_coding_gene | Not Applicable | UniProt/TrEMBL:O96509     UniProt/TrEMBL:Q5BHW5     UniProt/TrEMBL:Q7KPH5
FBgn0003523 | Ste | SO0001217:protein_coding_gene | Not Applicable | UniProt/GCRP:Q7KV12
FBgn0087003 | tal | SO0000690:gene_with_polycistronic_transcript | Not Applicable | none



</body>

</html>

- But there are a few that we want in the gpi that don't have DBxrefs to uniprot or RNAcentral, such as FBgns with component genes, as these will be represented in the gpi 'canonical form' column as a 'parent' for the component genes. 


This only applies to 3 FBgns:
5SrRNA FBgn0000002	SO0002238:cytosolic_rRNA_5S_gene Not Applicable
Su(Ste) FBgn0003582	SO0005851:gene_array Unannotated
tal FBgn0087003	SO0000690:gene_with_polycistronic_transcript Not Applicable

In these instances, could just use the SO gene type ID they have. But means that we will have some entities that are not gene products but gene types, but as just a handful and we are using PRO for proteins, not a biggie?

- For all ncRNAs in the GAF, use the corresponding SO ID.

rRNA	SO:0000252
SRP_RNA	SO:0000590
RNase_MRP_RNA	SO:0000385
RNase_P_RNA	SO:0000386
lncRNA	SO:0001877
miRNA	SO:0000276
tRNA	SO:0000253
sbRNA	SO:0002354
snoRNA	SO:0000275
snRNA	SO:0000274

- For all protein coding genes, use  PR:000000001

**Comment by hattrill** [comment]
Discussion with Steven and Giulia about removal of 'non-CG' associated GO annotations:

1. Justification
2. Breakdown of numbers
3. Avoiding loss of data?
4. Analysis of potential 'high value MFs'
5. Are BPs catured by phenotype anyway?
6. Can some of these genes be removed or merged during/after GO clean up?
7. Which MODs have similar non-mapped genes with GO annotations? (only know of WB)
8. What impact on users

**Comment by hattrill** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/hla28/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/hla28/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

</head>

<body link="#467886" vlink="#96607D">


  | MF | BP | CC | TOTAL
-- | -- | -- | -- | --
root annotations | 856 | 27 | 853 | 1736
non-root annotations | 94 | 867 | 101 | **1062**
total | 950 | 894 | 954 | 2798



</body>

</html>

Therefore only **1062** GO annotations for this set to 732 unannotated genes.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/hla28/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/hla28/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

</head>

<body link="#467886" vlink="#96607D">


Status = NA | Annotations
-- | --
5SrRNA | 1
His1 | 14
His2A | 20
His2B | 10
His3 | 11
His4 | 5
Sdic | 2
Ste | 13
tal | 5
TOTAL | 81
of which are IEA or IBA | 34*

*these are the only IEA/IBAs to unannotated genes (as these have UniProtKB mapping)


</body>

</html>

So, 981 annotations to review

**Comment by sjm41** [comment]
Thanks Helen! In further discussions (with the wider group), I wouldn't even mention the root annotations and just present the stats for the non-root annotations (total = 1,062) and genes.

**Comment by hattrill** [comment]
- [x] Need some guidance from GO about whether to use gene or gene product encoded ID for GPIv2.0
Use [candidate_gene SO:0001867](http://www.sequenceontology.org/browser/current_release/term/SO:0001867) for gene_product where gene was used
-use gene array etc for other genes mentioned about
-use the actual gene product for conventional mapped genes e.g. protein, snoRNA
- [x] How to spec CPX entries as do not necessarily want to make the annotation to FBgg
Use FBgg as primary ID and CPX as dbxref, then GOC can decide what to convert to ie use the CPX ID or the MOD ID (discuss on the 4th at annotation meeting)

**Comment by hattrill** [comment]
[QC FlyBase GPI files for new GOA-GOC data exchange pipeline #103](https://github.com/geneontology/go-releases/issues/103)

**Comment by hattrill** [comment]
Following up on our GPI discussion yesterday about GPIs, I spoke to Alex today and he suggests we make the cross-reference mandatory (col 10, see https://geneontology.org/docs/gene-product-information-gpi-format-2.0/), even if it repeats what’s in Column 1. The idea is that would make QC much easier. 

- [ ] Do this for GPI v2.0

**Comment by hattrill** [comment]
Chase duplication issue for Noctua import: see https://www.ebi.ac.uk/internal-tools/protein2go/dynamic.html?database=production#ac=Q9W1K0

**Comment by hattrill** [comment]
Noting issue for reimport - some ISS not mapping as not to GCRP version e.g. https://www.ebi.ac.uk/internal-tools/protein2go/dynamic.html?database=production#ac=Q9VLL5 see this fix

**Comment by hattrill** [comment]
Also to check for email exchange with GiL:
Hi Helen,

Other than [Or85e](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fflybase.org%2Freports%2FFBgn0026399&data=05%7C02%7Chla28%40universityofcambridgecloud.onmicrosoft.com%7Cdc3f40b7b3dc4b17124808ddf0778efb%7C49a50445bdfa4b79ade3547b4f3986e9%7C1%7C0%7C638931118473622258%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=A29GKx66Y6x%2BZprnTGhXkAL5Dh%2Fwxn723kWfFQmZBw0%3D&reserved=0), the only other gene in chado that has SwissProt xrefs but a TrEMBL GCRP xref is [Ste](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fflybase.org%2Freports%2FFBgn000323&data=05%7C02%7Chla28%40universityofcambridgecloud.onmicrosoft.com%7Cdc3f40b7b3dc4b17124808ddf0778efb%7C49a50445bdfa4b79ade3547b4f3986e9%7C1%7C0%7C638931118473646410%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=gRydC9HG9scfPSppzb89HVRWcI2gCv224vczeRWaCfA%3D&reserved=0) (FBgn0003523). The GCRP xref is [Q7KV18](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.uniprot.org%2Funiprotkb%2FQ7KV18%2Fentry&data=05%7C02%7Chla28%40universityofcambridgecloud.onmicrosoft.com%7Cdc3f40b7b3dc4b17124808ddf0778efb%7C49a50445bdfa4b79ade3547b4f3986e9%7C1%7C0%7C638931118473661026%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=iDsDb0lleRLVRdYBRVG3BDMeYcrm%2FXc1B8wyoZ1hkYs%3D&reserved=0), which looks like a SwissProt entry, but is unreviewed.

 uniquename  | name  |         SwissProt         |        TrEMBL         
-------------+-------+---------------------------+-------------------------
 FBgn0003523 | Ste   | UniProt/Swiss-Prot:Q7KV12 | UniProt/GCRP:Q7KV18
 FBgn0003523 | Ste   | UniProt/Swiss-Prot:Q7KV13 | UniProt/GCRP:Q7KV18
 FBgn0003523 | Ste   | UniProt/Swiss-Prot:Q7KV14 | UniProt/GCRP:Q7KV18
 FBgn0003523 | Ste   | UniProt/Swiss-Prot:Q7KV15 | UniProt/GCRP:Q7KV18
 FBgn0003523 | Ste   | UniProt/Swiss-Prot:Q7KV19 | UniProt/GCRP:Q7KV18
 FBgn0003523 | Ste   | UniProt/Swiss-Prot:Q7KV22 | UniProt/GCRP:Q7KV18
 FBgn0003523 | Ste   | UniProt/Swiss-Prot:Q7KV23 | UniProt/GCRP:Q7KV18
 FBgn0026399 | Or85e | UniProt/Swiss-Prot:P81924 | UniProt/GCRP:A0A0B4KGT9
(8 rows)

On Wed, Sep 10, 2025 at 9:42 AM Helen Attrill <[hla28@cam.ac.uk](mailto:hla28@cam.ac.uk)> wrote:

    Hi Steven, Gil,

    Are you aware of any examples of a FBgn having a SwissProt entry, but a different (TrEMBL) ID selected for the GCRP?

    I have one example of [FBgn0026399](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpreview.flybase.org%2Freports%2FFBgn0026399%23crossreferences&data=05%7C02%7Chla28%40universityofcambridgecloud.onmicrosoft.com%7Cdc3f40b7b3dc4b17124808ddf0778efb%7C49a50445bdfa4b79ade3547b4f3986e9%7C1%7C0%7C638931118473677169%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=jAhfF%2BXX8G9SNyCbCwzBBP08amBx7dKJzg8hFkptJoc%3D&reserved=0) (which needs to fixed by UniProt), but was wondering if you had come across any in your FlyCyc submission?

    Thanks,

    Helen

Note that it is a cluster thing:
FBgn0003523 	Ste 	SO0001217:protein_coding_gene 	Not Applicable 	UniProt/GCRP:Q7KV12

**Comment by hattrill** [comment]
Issues on geneontology repo to be followed up:

- [x] Recheck [GCRP missing xrefs](https://docs.google.com/spreadsheets/d/1QBaJ84IRWp80oevGoLVgBCbHUSc9y_TwtNq8MHEUgKE/edit?gid=0#gid=0) to see if they would be fixed by [Dave's fixes for pp data in UniProt](https://docs.google.com/spreadsheets/d/1emHVsZS9bmJSMqtko7QdiI6-mcinFZPxB3UUZ4TAwYw/edit?pli=1&gid=1682483035#gid=1682483035).
->These will not be impacted by these fixes.
- [x] update comment on https://github.com/geneontology/go-releases/issues/137 to reflect the above
- [x] Make new ticket for FBggs appearing in GOex file go-releases/issues/160
- [x] GOA/GOEx pipeline: Multiple mapping causing an issue #159 Check that fix works after release
- [x] See email thread "Mapping of non-reference proteome fly trembl entries to the reference proteome" - Alex to remove all GO annotations associated with non-RP IDs "I was hopping to do one more release before I start chopping it out. The accessions only will disappear from UniPort in March. But if you think it's fine to do in now, I'll remove them."
- [x] Noctua pipeline causing issues> go-site/issues/2570 & go-releases/issues/138: check:
"With new filter settings:
 NUNI: before 10499 after 7907
 NFB: before 772 after 369
 NWB: before 421 after 367
This should be visible at the next release (currently being built)"
- [x] Check GOA/GOEx pipeline: Multiple mapping causing an issue #159 ; "will be fixed in January GOA release."
- [x] IC issues go-releases/issues/157

**Comment by hattrill** [comment]
see https://docs.google.com/spreadsheets/d/1-yyFXTo4XLjqLlcbg5WLpyoEd1rdQGHsmskTLX6o25E/edit?gid=0#gid=0 for updates to missing xrefs

**Comment by hattrill** [comment]
see https://github.com/FlyBase/GO-curation/issues/214 for resolutions
