### ISSUE TITLE
Checklist for new DRSC "Gene Set Enrichment Tool"

### ISSUE THREAD

**Issue by gantonazzo** [FlyBase/GO-curation#37]
The tool can be found here: https://www.flyrnai.org/tools/enrichment_tool/web/home/7227
This ticket is to keep track of various tasks needed before signing-off the tool:
- [x] discuss with IU/WebDev a way to send list of genes from FlyBase to the external tool
- [x] figure out status of Alliance phenotype working group - any progress on a unified cross-species phenotype ontology?
- [x] provide use cases
- [x] test out the tool (and maybe also recruit testers from other databases?)
- [x] create Google document to collect suggestions and report bugs
(l[ast version](https://docs.google.com/spreadsheets/d/1XFVunqYeH7qow39dCwvQ-69wQp0gSM15c5q_ELKKp2M/edit#gid=0))
- [x] think of any other potentially useful gene set to add
- [x] check ComplexPortal migration status, and whether it could be a useful set
- [x] check with Claire about updating sets

**Comment by hattrill** [comment]
Subsets from GO release 2022-07-01
Contains Fly and GOC subets:
[2022_SUBSET.xlsx](https://github.com/FlyBase/GO-curation/files/9141709/2022_SUBSET.xlsx)

I think that for the fly enrichment, we could have both the generic and fly subsets option - might as well have the choice to tailor it for flies.

Also, we should think about excluding any direct annotations to GO:0070062 extracellular exosome as this is causing massive problems with CC enrichment in the human set when enriching using the relationships in the ontology to "map up":
<img width="392" alt="Exosome_issue" src="https://user-images.githubusercontent.com/11865746/179770583-a05e2933-85e0-4eae-8afb-6ab6795c0251.png">

**Comment by hattrill** [comment]
D.mel Complexes in Complex Portal 
https://docs.google.com/spreadsheets/d/1TbRJ9Xv7fhP_6cR0OAxzWnwuQvBSCgNyoCsW-YvYDFk/edit#gid=0
https://docs.google.com/spreadsheets/d/1YkDmmQLezHmq7_yEns3ei4EP4qdJZM5nALgBsauK1yo/edit?pli=1#gid=0

**Comment by hattrill** [comment]
Phenotypes: Giulia emailed Arzu. Central message: harmonisation efforts for phenotypic data are currently on hold at the Alliance.

**Comment by hattrill** [comment]
EMAIL CORRESPNDANCE WITH CH:
from HA:
While I am thinking about it, I compared the generic GOC subset (formally known as slims) and the fly subset and I think that there is some value in having the generic one for all species but for fly having both the generic one and the fly tailored subsets as a choice.

I also think that it might be worthwhile excluding annotations directly GO:0070062 extracellular exosome - this is causing massive problems with CC enrichment in the human as UniProt did a huge project annotating exosome datasets - it was never appropriate to use the GO for this! - have had discussions with the GOC on how to solve this - it always comes out as the top enriched term and because of the structure of the ontology, it also makes it look like all these proteins are extracellular! I've had a couple of cases where I've had to help human researchers interpret their enrichment results because of this. This is not a problem for most other species - but causes real confusion with human CC data.

We also discussed the ComplexPortal as a geneset and we think that this would be worthwhile. I am having a look over the fly data in  CP at the moment to cross-check it with our complexes.

For phenotypes: Giulia emailed Arzu who is on the Alliance Working group for this. The central message is that harmonisation efforts for phenotypic data are currently on hold at the Alliance. So perhaps this is a "for the future" thing and "not a now" thing.

Reply: CH
 1.) SLIM:  we will keep 2 SLIM sets for fly
2.) I just looked at our database and confirmed that "GO:0070062" is indeed very different for human than other species.  There are about 2k human genes associated with this GO while only a few hundred for mouse and 2 digits for fly and zebrafish.  We will remove the human gene sets associated with this term.
3.) We will add the complex annotation from ComplexPortal.
4.) Phenotype annotation: adding phenotype gene sets for other species will happen in the future when AGR provides such annotation.  Shall we consider adding the fly phenotype sets?  If so,  we will need some help getting the info from FlyBase.

**Comment by gantonazzo** [comment]
Jira ticket in place for Jim/IU for the pre-population of the enrichment tool input gene list from FB: https://flybase.atlassian.net/browse/WEB-2028

**Comment by hattrill** [comment]
Linking to first round of improvements sent to Claire https://docs.google.com/document/d/1U6l7OWG-5t3st-i2HZNDG0ObH5MBhh6LDS67MS4tC98/edit

**Comment by hattrill** [comment]
Linking to [Cam group meeting](https://docs.google.com/presentation/d/1BJ65loyk47bKiBj9bPsg76USR3iflVebnrSOmSu-AnA/edit#slide=id.p) discusssing barriers to using pheno file for us and pheno file reforms in general

**Comment by hattrill** [comment]
Gil has made new pheno file as spec's in https://docs.google.com/presentation/d/1Ad8eX_KMf7U5wqzzOaYZX5-DvTVUcJ-bmS5aCVK4EUs/edit#slide=id.g16ce49be32b_0_2
and on Jira DB-813
[genotype_phenotype_report_fb_2022_06_reporting_2.tsv.gz](https://github.com/FlyBase/GO-curation/files/10132692/genotype_phenotype_report_fb_2022_06_reporting_2.tsv.gz)

**Comment by hattrill** [comment]
What FBcv terms should be used for enrichment tool?
"single_nobal_noFBti_v2_NoTn_NoANAT_Dmel" File of 'single allele Dmel FBcv' only
[single_nobal_noFBti_v2_NoTn_NoANAT_dmel.txt](https://github.com/FlyBase/GO-curation/files/10133320/single_nobal_noFBti_v2_NoTn_NoANAT_dmel.txt)


Only terms under phenotype FBcv:0001347

**Comment by hattrill** [comment]
Flattened list,but only to 95 terms.
[phenotypic_class_nameid_subset.txt](https://github.com/FlyBase/GO-curation/files/10133686/phenotypic_class_nameid_subset.txt)
Give this set to DRSC. They can try using  only terms under phenotype FBcv:0001347 and this subset
